Category.create(name:'シャツ', url:'S')
Category.create(name:'シャツ', url:'M')
Category.create(name:'シャツ', url:'L')
Category.create(name:'シャツ', url:'S')
Genre.create(name:'メンズ')
Genre.create(name:'レディース')
Genre.create(name:'キッズ')
